#!/usr/bin/env python3
"""
WORKING SMS System for Jeremy's AI Business
Monitors jeremy@kermiclemedia.com for Google Voice forwards and responds professionally
"""

import time
import json
import os
from datetime import datetime, timedelta
from google.oauth2 import service_account
from googleapiclient.discovery import build
import base64
import re

class WorkingSMSSystem:
    def __init__(self):
        self.phone = "(859) 428-7481"
        self.business_email = "jeremy@kermiclemedia.com" 
        self.credentials_path = "gmail_credentials.json"
        self.service = None
        self.processed_messages = set()
        
    def log(self, message):
        timestamp = datetime.now().strftime("%H:%M:%S")
        print(f"[{timestamp}] {message}")
        
    def setup_gmail(self):
        try:
            credentials = service_account.Credentials.from_service_account_file(
                self.credentials_path,
                scopes=[
                    'https://www.googleapis.com/auth/gmail.readonly',
                    'https://www.googleapis.com/auth/gmail.send',
                    'https://www.googleapis.com/auth/gmail.modify'
                ]
            )
            
            # For service account to access user Gmail, we need delegation
            # But let's try direct access first and see what happens
            delegated_credentials = credentials.with_subject(self.business_email)
            self.service = build('gmail', 'v1', credentials=delegated_credentials)
            self.log("✅ Gmail service connected successfully")
            return True
            
        except Exception as e:
            self.log(f"❌ Gmail setup failed: {e}")
            return False
    
    def get_recent_emails(self):
        try:
            # Search for Google Voice SMS forwards in the last hour
            one_hour_ago = (datetime.now() - timedelta(hours=1)).strftime('%Y/%m/%d')
            
            query = f'from:txt.voice.google.com OR from:voice-noreply@google.com OR subject:"text message" after:{one_hour_ago}'
            
            result = self.service.users().messages().list(
                userId='me', 
                q=query,
                maxResults=10
            ).execute()
            
            messages = result.get('messages', [])
            self.log(f"Found {len(messages)} potential SMS emails")
            return messages
            
        except Exception as e:
            self.log(f"❌ Error getting emails: {e}")
            return []
    
    def parse_sms_content(self, msg_data):
        try:
            # Extract message body
            payload = msg_data['payload']
            body = ""
            
            if 'parts' in payload:
                for part in payload['parts']:
                    if part['mimeType'] == 'text/plain':
                        if 'data' in part['body']:
                            body = base64.urlsafe_b64decode(part['body']['data']).decode('utf-8')
                            break
            else:
                if payload['mimeType'] == 'text/plain' and 'data' in payload['body']:
                    body = base64.urlsafe_b64decode(payload['body']['data']).decode('utf-8')
            
            # Extract phone number and message from Google Voice format
            sms_match = re.search(r'from (\(?\d{3}\)?\s*-?\d{3}-?\d{4}).*?Message: (.+)', body, re.DOTALL)
            if sms_match:
                sender_phone = sms_match.group(1).strip()
                message_content = sms_match.group(2).strip()
                return sender_phone, message_content
            
            return None, None
            
        except Exception as e:
            self.log(f"❌ Error parsing SMS: {e}")
            return None, None
    
    def generate_ai_response(self, sender_phone, message_content):
        # Professional AI automation business response
        response = f"""Hi there!

Thank you for texting Kermicle Media at {self.phone}. I received your message: "{message_content}"

I'm Jeremy Kermicle, and I help Northern Kentucky businesses eliminate 15-20 hours per week of manual tasks through AI automation. Our packages start at $2,200 and typically provide full ROI within 4-8 months.

I'd love to show you exactly how AI automation can transform your business operations. Would you like to schedule a free 30-minute consultation?

You can reply to this email or call me directly at {self.phone}.

Best regards,
Jeremy Kermicle
Kermicle Media
jeremy@kermiclemedia.com
{self.phone}

P.S. This response was generated by my AI system - a small example of the automation capabilities I can implement for your business!"""

        return response
    
    def send_response_email(self, recipient_phone, message_content, response):
        try:
            # Create email message
            message = {
                'raw': base64.urlsafe_b64encode(
                    f'To: {recipient_phone}@sms.kermiclemedia.com\n'
                    f'From: jeremy@kermiclemedia.com\n'
                    f'Subject: Response to Your Text Message to {self.phone}\n'
                    f'Content-Type: text/plain; charset=utf-8\n\n'
                    f'{response}'.encode('utf-8')
                ).decode('utf-8')
            }
            
            # Send via Gmail API
            sent = self.service.users().messages().send(userId='me', body=message).execute()
            self.log(f"✅ Response sent successfully (Message ID: {sent['id']})")
            return True
            
        except Exception as e:
            self.log(f"❌ Error sending response: {e}")
            return False
    
    def process_sms_messages(self):
        messages = self.get_recent_emails()
        
        for msg in messages:
            msg_id = msg['id']
            
            # Skip if already processed
            if msg_id in self.processed_messages:
                continue
                
            try:
                # Get full message
                msg_data = self.service.users().messages().get(userId='me', id=msg_id).execute()
                
                # Parse SMS content
                sender_phone, message_content = self.parse_sms_content(msg_data)
                
                if sender_phone and message_content:
                    self.log(f"📱 New SMS from {sender_phone}: {message_content[:50]}...")
                    
                    # Generate AI response
                    response = self.generate_ai_response(sender_phone, message_content)
                    
                    # Send professional response
                    if self.send_response_email(sender_phone, message_content, response):
                        self.processed_messages.add(msg_id)
                        self.log("🎯 SMS processed successfully!")
                    
            except Exception as e:
                self.log(f"❌ Error processing message {msg_id}: {e}")
    
    def start_monitoring(self):
        self.log("🚀 Starting Kermicle Media SMS System")
        self.log(f"📱 Business Phone: {self.phone}")
        self.log(f"📧 Business Email: {self.business_email}")
        
        if not self.setup_gmail():
            self.log("❌ Gmail setup failed - cannot start SMS system")
            return
            
        self.log("✅ SMS System Active - Monitoring for business inquiries")
        
        try:
            while True:
                self.log("🔍 Checking for new SMS messages...")
                self.process_sms_messages()
                self.log("✅ Check complete - waiting 2 minutes...")
                time.sleep(120)  # Check every 2 minutes
                
        except KeyboardInterrupt:
            self.log("🛑 SMS System stopped by user")

if __name__ == "__main__":
    print("========================================")
    print("  🚀 KERMICLE MEDIA SMS SYSTEM")
    print("========================================")
    print()
    
    sms_system = WorkingSMSSystem()
    sms_system.start_monitoring()