-- ItemDatabase.lua (ModuleScript in ReplicatedStorage/Modules)
-- Every item in the game defined here

local ItemDatabase = {}

ItemDatabase.Items = {
	-- === ORES (from Mining) ===
	["Copper Ore"] = {
		id = "copper_ore",
		type = "resource",
		rarity = "common",
		skill = "Mining",
		levelReq = 1,
		xp = 20,
		stackable = true,
		value = 5,
		description = "A chunk of copper ore.",
	},
	["Iron Ore"] = {
		id = "iron_ore",
		type = "resource",
		rarity = "uncommon",
		skill = "Mining",
		levelReq = 15,
		xp = 35,
		stackable = true,
		value = 15,
		description = "A chunk of iron ore.",
	},
	["Tin Ore"] = {
		id = "tin_ore",
		type = "resource",
		rarity = "common",
		skill = "Mining",
		levelReq = 1,
		xp = 25,
		stackable = true,
		value = 8,
		description = "A chunk of tin ore. Used with copper to make bronze.",
	},
	["Coal Ore"] = {
		id = "coal_ore",
		type = "resource",
		rarity = "uncommon",
		skill = "Mining",
		levelReq = 30,
		xp = 50,
		stackable = true,
		value = 25,
		description = "A lump of coal. Essential for smelting.",
	},
	["Mithril Ore"] = {
		id = "mithril_ore",
		type = "resource",
		rarity = "rare",
		skill = "Mining",
		levelReq = 55,
		xp = 80,
		stackable = true,
		value = 100,
		description = "A shimmering mithril ore. Light but strong.",
	},
	["Adamant Ore"] = {
		id = "adamant_ore",
		type = "resource",
		rarity = "epic",
		skill = "Mining",
		levelReq = 70,
		xp = 95,
		stackable = true,
		value = 150,
		description = "A dense adamantite ore. Extremely durable.",
	},
	["Gold Ore"] = {
		id = "gold_ore",
		type = "resource",
		rarity = "rare",
		skill = "Mining",
		levelReq = 40,
		xp = 65,
		stackable = true,
		value = 50,
		description = "A chunk of gold ore. Valuable.",
	},
	["Runite Ore"] = {
		id = "runite_ore",
		type = "resource",
		rarity = "epic",
		skill = "Mining",
		levelReq = 70,
		xp = 125,
		stackable = true,
		value = 200,
		description = "Extremely rare ore. Only found in the Wilderness.",
		wildernessOnly = true,
	},

	-- === LOGS (from Woodcutting) ===
	["Oak Log"] = {
		id = "oak_log",
		type = "resource",
		rarity = "common",
		skill = "Woodcutting",
		levelReq = 1,
		xp = 18,
		stackable = true,
		value = 4,
		description = "A sturdy oak log.",
	},
	["Willow Log"] = {
		id = "willow_log",
		type = "resource",
		rarity = "uncommon",
		skill = "Woodcutting",
		levelReq = 20,
		xp = 40,
		stackable = true,
		value = 12,
		description = "A flexible willow log.",
	},
	["Yew Log"] = {
		id = "yew_log",
		type = "resource",
		rarity = "rare",
		skill = "Woodcutting",
		levelReq = 50,
		xp = 80,
		stackable = true,
		value = 75,
		description = "Dense yew wood. Prized by fletchers.",
	},
	["Magic Log"] = {
		id = "magic_log",
		type = "resource",
		rarity = "epic",
		skill = "Woodcutting",
		levelReq = 75,
		xp = 150,
		stackable = true,
		value = 250,
		description = "Pulsing with energy. Wilderness only.",
		wildernessOnly = true,
	},

	-- === FISH (from Fishing) ===
	["Shrimp"] = {
		id = "shrimp",
		type = "resource",
		skill = "Fishing",
		levelReq = 1,
		xp = 15,
		stackable = true,
		value = 3,
		cookable = true,
		healAmount = 5,
		description = "A small shrimp.",
	},
	["Trout"] = {
		id = "trout",
		type = "resource",
		skill = "Fishing",
		levelReq = 20,
		xp = 35,
		stackable = true,
		value = 10,
		cookable = true,
		healAmount = 15,
		description = "A fresh trout.",
	},
	["Lobster"] = {
		id = "lobster",
		type = "resource",
		skill = "Fishing",
		levelReq = 40,
		xp = 60,
		stackable = true,
		value = 40,
		cookable = true,
		healAmount = 30,
		description = "A large lobster.",
	},
	["Salmon"] = {
		id = "salmon",
		type = "resource",
		skill = "Fishing",
		levelReq = 30,
		xp = 45,
		stackable = true,
		value = 15,
		cookable = true,
		healAmount = 20,
		description = "A fresh salmon. Good for cooking.",
	},
	["Swordfish"] = {
		id = "swordfish",
		type = "resource",
		skill = "Fishing",
		levelReq = 50,
		xp = 75,
		stackable = true,
		value = 60,
		cookable = true,
		healAmount = 40,
		description = "A swordfish with a long, sharp bill.",
	},
	["Shark"] = {
		id = "shark",
		type = "resource",
		skill = "Fishing",
		levelReq = 70,
		xp = 110,
		stackable = true,
		value = 150,
		cookable = true,
		healAmount = 60,
		description = "A fearsome shark. Provides a lot of meat.",
	},
	["Dark Crab"] = {
		id = "dark_crab",
		type = "resource",
		skill = "Fishing",
		levelReq = 70,
		xp = 130,
		stackable = true,
		value = 180,
		cookable = true,
		healAmount = 50,
		description = "Found only in Wilderness waters.",
		wildernessOnly = true,
	},

	-- === BARS (from Smithing) ===
	["Copper Bar"] = {
		id = "copper_bar",
		type = "crafted",
		skill = "Smithing",
		levelReq = 1,
		xp = 25,
		stackable = true,
		value = 12,
		recipe = { ["Copper Ore"] = 1 },
		description = "A smelted copper bar.",
	},
	["Iron Bar"] = {
		id = "iron_bar",
		type = "crafted",
		skill = "Smithing",
		levelReq = 15,
		xp = 45,
		stackable = true,
		value = 35,
		recipe = { ["Iron Ore"] = 1 },
		description = "A smelted iron bar.",
	},
	["Gold Bar"] = {
		id = "gold_bar",
		type = "crafted",
		skill = "Smithing",
		levelReq = 40,
		xp = 75,
		stackable = true,
		value = 120,
		recipe = { ["Gold Ore"] = 1 },
		description = "A gleaming gold bar.",
	},

	-- === WEAPONS ===
	["Copper Sword"] = {
		id = "copper_sword",
		type = "weapon",
		equipSlot = "Weapon",
		skill = "Smithing",
		levelReq = 1,
		combatReq = 1,
		xp = 50,
		stackable = false,
		value = 30,
		damage = 8,
		attackSpeed = 1.5,
		recipe = { ["Copper Bar"] = 2 },
		description = "A basic copper sword.",
	},
	["Iron Sword"] = {
		id = "iron_sword",
		type = "weapon",
		equipSlot = "Weapon",
		skill = "Smithing",
		levelReq = 20,
		combatReq = 15,
		xp = 80,
		stackable = false,
		value = 85,
		damage = 15,
		attackSpeed = 1.4,
		recipe = { ["Iron Bar"] = 2 },
		description = "A solid iron blade.",
	},
	["Gold Sword"] = {
		id = "gold_sword",
		type = "weapon",
		equipSlot = "Weapon",
		skill = "Smithing",
		levelReq = 45,
		combatReq = 40,
		xp = 120,
		stackable = false,
		value = 300,
		damage = 25,
		attackSpeed = 1.3,
		recipe = { ["Gold Bar"] = 3 },
		description = "A powerful gold sword.",
	},

	-- === COOKED FOOD ===
	["Cooked Shrimp"] = {
		id = "cooked_shrimp",
		type = "food",
		skill = "Cooking",
		levelReq = 1,
		xp = 20,
		stackable = true,
		value = 8,
		healAmount = 10,
		recipe = { ["Shrimp"] = 1 },
		description = "Heals 10 HP.",
	},
	["Cooked Trout"] = {
		id = "cooked_trout",
		type = "food",
		skill = "Cooking",
		levelReq = 20,
		xp = 40,
		stackable = true,
		value = 25,
		healAmount = 25,
		recipe = { ["Trout"] = 1 },
		description = "Heals 25 HP.",
	},
	["Cooked Lobster"] = {
		id = "cooked_lobster",
		type = "food",
		skill = "Cooking",
		levelReq = 40,
		xp = 65,
		stackable = true,
		value = 90,
		healAmount = 45,
		recipe = { ["Lobster"] = 1 },
		description = "Heals 45 HP.",
	},
	["Cooked Salmon"] = {
		id = "cooked_salmon",
		type = "food",
		skill = "Cooking",
		levelReq = 30,
		xp = 50,
		stackable = true,
		value = 35,
		healAmount = 30,
		recipe = { ["Salmon"] = 1 },
		description = "Heals 30 HP.",
	},
	["Cooked Swordfish"] = {
		id = "cooked_swordfish",
		type = "food",
		skill = "Cooking",
		levelReq = 50,
		xp = 80,
		stackable = true,
		value = 120,
		healAmount = 55,
		recipe = { ["Swordfish"] = 1 },
		description = "Heals 55 HP.",
	},
	["Cooked Shark"] = {
		id = "cooked_shark",
		type = "food",
		skill = "Cooking",
		levelReq = 70,
		xp = 120,
		stackable = true,
		value = 300,
		healAmount = 80,
		recipe = { ["Shark"] = 1 },
		description = "Heals 80 HP.",
	},
	["Cooked Dark Crab"] = {
		id = "cooked_dark_crab",
		type = "food",
		skill = "Cooking",
		levelReq = 70,
		xp = 140,
		stackable = true,
		value = 350,
		healAmount = 70,
		recipe = { ["Dark Crab"] = 1 },
		description = "Heals 70 HP. The best food in the game.",
	},

	-- === BASIC FOOD & SUPPLIES ===
	["Bread"] = {
		id = "bread",
		type = "food",
		stackable = true,
		value = 10,
		healAmount = 3,
		description = "Simple bread. Heals 3 HP.",
	},
	["Meat Pie"] = {
		id = "meat_pie",
		type = "food",
		stackable = true,
		value = 25,
		healAmount = 8,
		description = "A hearty meat pie. Heals 8 HP.",
	},
	["Healing Potion"] = {
		id = "healing_potion",
		type = "food",
		stackable = true,
		value = 50,
		healAmount = 15,
		description = "A magical healing potion. Heals 15 HP.",
	},
	["Fishing Bait"] = {
		id = "fishing_bait",
		type = "material",
		stackable = true,
		value = 3,
		description = "Essential for fishing. Attracts fish.",
	},
	["Rope"] = {
		id = "rope",
		type = "material",
		stackable = true,
		value = 15,
		description = "Strong rope. Useful for various tasks.",
	},
	["Tinderbox"] = {
		id = "tinderbox",
		type = "tool",
		stackable = true,
		value = 8,
		description = "Used to start fires. Essential for cooking.",
	},

	-- === BURNT FOOD ===
	["Burnt Shrimp"] = {
		id = "burnt_shrimp", type = "junk", stackable = true, value = 1,
		description = "Oops. Completely inedible.",
	},
	["Burnt Trout"] = {
		id = "burnt_trout", type = "junk", stackable = true, value = 1,
		description = "A blackened trout. Smells terrible.",
	},
	["Burnt Lobster"] = {
		id = "burnt_lobster", type = "junk", stackable = true, value = 1,
		description = "A charred lobster. Not appetizing.",
	},
	["Burnt Dark Crab"] = {
		id = "burnt_dark_crab", type = "junk", stackable = true, value = 1,
		description = "An overcooked dark crab. What a waste.",
	},

	-- === MONSTER DROPS ===
	["Feather"] = {
		id = "feather",
		type = "resource",
		stackable = true,
		value = 2,
		description = "A soft feather.",
	},
	["Raw Chicken"] = {
		id = "raw_chicken",
		type = "resource",
		skill = "Cooking",
		levelReq = 1,
		xp = 15,
		cookable = true,
		healAmount = 3,
		value = 3,
		description = "Raw chicken meat.",
	},
	["Cooked Chicken"] = {
		id = "cooked_chicken",
		type = "food",
		stackable = true,
		value = 8,
		healAmount = 8,
		recipe = { ["Raw Chicken"] = 1 },
		description = "Heals 8 HP.",
	},
	["Cowhide"] = {
		id = "cowhide",
		type = "resource",
		stackable = true,
		value = 5,
		description = "Can be crafted into leather.",
	},
	["Raw Beef"] = {
		id = "raw_beef",
		type = "resource",
		skill = "Cooking",
		levelReq = 1,
		xp = 18,
		cookable = true,
		healAmount = 4,
		value = 4,
		description = "A slab of raw beef.",
	},
	["Cooked Beef"] = {
		id = "cooked_beef",
		type = "food",
		stackable = true,
		value = 12,
		healAmount = 12,
		recipe = { ["Raw Beef"] = 1 },
		description = "Heals 12 HP.",
	},
	["Goblin Mail"] = {
		id = "goblin_mail",
		type = "armor",
		equipSlot = "Body",
		combatReq = 1,
		stackable = false,
		value = 25,
		defense = 3,
		description = "Crude goblin armor.",
	},
	["Bones"] = {
		id = "bones",
		type = "resource",
		stackable = true,
		value = 3,
		description = "Can be buried for Prayer XP.",
	},
	["Dog Tag"] = {
		id = "dog_tag",
		type = "resource",
		stackable = true,
		value = 50,
		description = "A shiny dog tag. Rare collectible.",
	},
	["Rat Tail"] = {
		id = "rat_tail",
		type = "resource",
		stackable = true,
		value = 5,
		description = "Gross but useful for potions.",
	},
	["Raw Rat Meat"] = {
		id = "raw_rat_meat",
		type = "resource",
		skill = "Cooking",
		levelReq = 1,
		xp = 10,
		cookable = true,
		healAmount = 2,
		value = 2,
		description = "Not appetizing.",
	},
	["Cooked Rat Meat"] = {
		id = "cooked_rat_meat",
		type = "food",
		stackable = true,
		value = 5,
		healAmount = 5,
		recipe = { ["Raw Rat Meat"] = 1 },
		description = "Barely edible. Heals 5 HP.",
	},
	["Wizard Robe"] = {
		id = "wizard_robe",
		type = "armor",
		equipSlot = "Body",
		combatReq = 30,
		stackable = false,
		value = 200,
		defense = 12,
		description = "Enchanted wizard robes.",
	},
	["Demon Heart"] = {
		id = "demon_heart",
		type = "resource",
		stackable = true,
		value = 500,
		description = "Pulsing with dark energy.",
	},
	["Dragon Scale"] = {
		id = "dragon_scale",
		type = "resource",
		stackable = true,
		value = 1000,
		description = "Nearly indestructible.",
	},
	["Dragon Sword"] = {
		id = "dragon_sword",
		type = "weapon",
		equipSlot = "Weapon",
		combatReq = 75,
		stackable = false,
		value = 5000,
		damage = 50,
		attackSpeed = 1.1,
		description = "Forged from dragon fire.",
	},
	["Shadow Gem"] = {
		id = "shadow_gem",
		type = "resource",
		stackable = true,
		value = 2000,
		description = "Radiates shadow energy.",
	},
	["Bronze Helmet"] = {
		id = "bronze_helmet",
		type = "armor",
		equipSlot = "Head",
		combatReq = 1,
		stackable = false,
		value = 20,
		defense = 2,
		description = "A basic bronze helmet.",
	},
	-- === LEG ARMOR (full tier set) ===
	["Bronze Platelegs"] = {
		id = "bronze_platelegs", type = "armor", equipSlot = "Legs",
		combatReq = 1, stackable = false, value = 20, defense = 3,
		description = "Basic bronze leg armor.",
	},
	["Iron Platelegs"] = {
		id = "iron_platelegs", type = "armor", equipSlot = "Legs",
		combatReq = 15, stackable = false, value = 60, defense = 8,
		description = "Sturdy iron leg armor.",
	},
	["Gold Platelegs"] = {
		id = "gold_platelegs", type = "armor", equipSlot = "Legs",
		combatReq = 30, stackable = false, value = 200, defense = 14,
		description = "Ornate gold-plated leg armor.",
	},
	["Runite Platelegs"] = {
		id = "runite_platelegs", type = "armor", equipSlot = "Legs",
		combatReq = 50, stackable = false, value = 800, defense = 22,
		description = "Powerful runite leg armor.",
	},
	["Dragon Platelegs"] = {
		id = "dragon_platelegs", type = "armor", equipSlot = "Legs",
		combatReq = 70, stackable = false, value = 3000, defense = 35,
		rarity = "legendary",
		description = "Legendary dragon leg armor, forged in dragonfire.",
	},

	-- === CHEST ARMOR (full tier set) ===
	["Bronze Platebody"] = {
		id = "bronze_platebody", type = "armor", equipSlot = "Body",
		combatReq = 1, stackable = false, value = 30, defense = 5,
		description = "Basic bronze chest plate.",
	},
	["Iron Platebody"] = {
		id = "iron_platebody", type = "armor", equipSlot = "Body",
		combatReq = 15, stackable = false, value = 80, defense = 12,
		description = "Solid iron chest armor.",
	},
	["Gold Platebody"] = {
		id = "gold_platebody", type = "armor", equipSlot = "Body",
		combatReq = 30, stackable = false, value = 300, defense = 20,
		description = "A gilded gold chest plate.",
	},
	["Runite Platebody"] = {
		id = "runite_platebody", type = "armor", equipSlot = "Body",
		combatReq = 50, stackable = false, value = 1200, defense = 30,
		description = "Elite runite chest armor.",
	},
	["Dragon Platebody"] = {
		id = "dragon_platebody", type = "armor", equipSlot = "Body",
		combatReq = 70, stackable = false, value = 5000, defense = 45,
		rarity = "legendary",
		description = "Legendary dragon chest armor, nearly indestructible.",
	},

	-- === CHAINMAIL (lighter body armor, lower defense but allows ranged) ===
	["Iron Chainbody"] = {
		id = "iron_chainbody", type = "armor", equipSlot = "Body",
		combatReq = 10, stackable = false, value = 40, defense = 6,
		description = "Light iron chainmail, good for rangers.",
	},
	["Gold Chainbody"] = {
		id = "gold_chainbody", type = "armor", equipSlot = "Body",
		combatReq = 25, stackable = false, value = 150, defense = 12,
		description = "Flexible gold chainmail.",
	},
	["Runite Chainbody"] = {
		id = "runite_chainbody", type = "armor", equipSlot = "Body",
		combatReq = 45, stackable = false, value = 600, defense = 20,
		description = "Strong yet flexible runite chainmail.",
	},

	-- === LEATHER ARMOR (ranger gear) ===
	["Leather Body"] = {
		id = "leather_body", type = "armor", equipSlot = "Body",
		combatReq = 1, stackable = false, value = 15, defense = 3,
		description = "Simple leather tunic.",
	},
	["Leather Chaps"] = {
		id = "leather_chaps", type = "armor", equipSlot = "Legs",
		combatReq = 1, stackable = false, value = 12, defense = 2,
		description = "Basic leather leg protection.",
	},
	["Studded Body"] = {
		id = "studded_body", type = "armor", equipSlot = "Body",
		combatReq = 20, stackable = false, value = 80, defense = 8,
		description = "Leather armor reinforced with metal studs.",
	},
	["Studded Chaps"] = {
		id = "studded_chaps", type = "armor", equipSlot = "Legs",
		combatReq = 20, stackable = false, value = 60, defense = 6,
		description = "Studded leather leg armor.",
	},
	["Dragonhide Body"] = {
		id = "dragonhide_body", type = "armor", equipSlot = "Body",
		combatReq = 60, stackable = false, value = 2000, defense = 28,
		rarity = "epic",
		description = "Armor crafted from dragon scales, prized by rangers.",
	},
	["Dragonhide Chaps"] = {
		id = "dragonhide_chaps", type = "armor", equipSlot = "Legs",
		combatReq = 60, stackable = false, value = 1500, defense = 22,
		rarity = "epic",
		description = "Leg armor from dragon scales, light and durable.",
	},

	-- Keep old Iron Legs as alias
	["Iron Legs"] = {
		id = "iron_legs", type = "armor", equipSlot = "Legs",
		combatReq = 15, stackable = false, value = 60, defense = 8,
		description = "Sturdy iron leg armor.",
	},
	["Wooden Shield"] = {
		id = "wooden_shield",
		type = "armor",
		equipSlot = "Shield",
		combatReq = 1,
		stackable = false,
		value = 15,
		defense = 2,
		description = "A simple wooden shield.",
	},
	["Bronze Coins"] = {
		id = "bronze_coins",
		type = "currency",
		stackable = true,
		value = 1,
		description = "Standard currency.",
	},

	-- === RANGED WEAPONS ===
	["Oak Shortbow"] = {
		id = "oak_shortbow",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 6,
		rangedReq = 1,
		stackable = false,
		value = 15,
		description = "A basic oak shortbow.",
	},
	["Oak Longbow"] = {
		id = "oak_longbow",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 10,
		rangedReq = 10,
		stackable = false,
		value = 30,
		description = "A sturdy oak longbow.",
	},
	["Willow Shortbow"] = {
		id = "willow_shortbow",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 12,
		rangedReq = 20,
		stackable = false,
		value = 50,
		description = "A flexible willow shortbow.",
	},
	["Iron Crossbow"] = {
		id = "iron_crossbow",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 18,
		rangedReq = 30,
		stackable = false,
		value = 100,
		recipe = { ["Iron Bar"] = 3 },
		description = "A powerful iron crossbow.",
	},
	["Willow Longbow"] = {
		id = "willow_longbow",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 18,
		rangedReq = 40,
		stackable = false,
		value = 120,
		description = "A long willow bow with great range.",
	},
	["Yew Shortbow"] = {
		id = "yew_shortbow",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 22,
		rangedReq = 55,
		stackable = false,
		value = 200,
		description = "A yew shortbow. Fast and accurate.",
	},
	["Gold Crossbow"] = {
		id = "gold_crossbow",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 28,
		rangedReq = 65,
		stackable = false,
		value = 400,
		recipe = { ["Gold Bar"] = 3 },
		description = "A gleaming gold crossbow.",
	},
	["Yew Longbow"] = {
		id = "yew_longbow",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 30,
		rangedReq = 70,
		stackable = false,
		value = 350,
		description = "A powerful yew longbow.",
	},
	["Magic Shortbow"] = {
		id = "magic_shortbow",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 35,
		rangedReq = 85,
		stackable = false,
		value = 800,
		description = "Imbued with magical energy.",
	},
	["Dragon Crossbow"] = {
		id = "dragon_crossbow",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 45,
		rangedReq = 95,
		stackable = false,
		value = 8000,
		description = "Forged from dragonfire. The ultimate ranged weapon.",
	},

	-- === AMMUNITION ===
	["Bronze Arrows"] = {
		id = "bronze_arrows",
		type = "ammo",
		stackable = true,
		bonusDmg = 1,
		value = 1,
		description = "Basic bronze-tipped arrows.",
	},
	["Iron Arrows"] = {
		id = "iron_arrows",
		type = "ammo",
		stackable = true,
		bonusDmg = 3,
		value = 3,
		description = "Iron-tipped arrows.",
	},
	["Steel Arrows"] = {
		id = "steel_arrows",
		type = "ammo",
		stackable = true,
		bonusDmg = 5,
		value = 5,
		description = "Steel-tipped arrows. Stronger than iron.",
	},
	["Mithril Arrows"] = {
		id = "mithril_arrows",
		type = "ammo",
		stackable = true,
		bonusDmg = 7,
		value = 12,
		description = "Mithril-tipped arrows. Light and deadly.",
	},
	["Adamant Arrows"] = {
		id = "adamant_arrows",
		type = "ammo",
		stackable = true,
		bonusDmg = 9,
		value = 18,
		description = "Adamantite-tipped arrows. Extremely powerful.",
	},
	["Gold Arrows"] = {
		id = "gold_arrows",
		type = "ammo",
		stackable = true,
		bonusDmg = 6,
		value = 8,
		description = "Gold-tipped arrows.",
	},
	["Runite Arrows"] = {
		id = "runite_arrows",
		type = "ammo",
		stackable = true,
		bonusDmg = 10,
		value = 25,
		description = "Runite-tipped arrows. Devastating.",
	},
	["Iron Bolts"] = {
		id = "iron_bolts",
		type = "ammo",
		stackable = true,
		bonusDmg = 4,
		value = 4,
		description = "Iron crossbow bolts.",
	},
	["Steel Bolts"] = {
		id = "steel_bolts",
		type = "ammo",
		stackable = true,
		bonusDmg = 6,
		value = 6,
		description = "Steel crossbow bolts. More penetration than iron.",
	},
	["Mithril Bolts"] = {
		id = "mithril_bolts",
		type = "ammo",
		stackable = true,
		bonusDmg = 9,
		value = 15,
		description = "Mithril crossbow bolts. Lightweight and accurate.",
	},
	["Gold Bolts"] = {
		id = "gold_bolts",
		type = "ammo",
		stackable = true,
		bonusDmg = 8,
		value = 10,
		description = "Gold crossbow bolts.",
	},
	["Runite Bolts"] = {
		id = "runite_bolts",
		type = "ammo",
		stackable = true,
		bonusDmg = 12,
		value = 30,
		description = "Runite crossbow bolts.",
	},
	["Bowstring"] = {
		id = "bowstring",
		type = "resource",
		stackable = true,
		value = 5,
		description = "Used for crafting bows.",
	},
	["Arrow Shafts"] = {
		id = "arrow_shafts",
		type = "resource",
		stackable = true,
		value = 1,
		description = "Used for crafting arrows.",
	},
	["Magic Bowstring"] = {
		id = "magic_bowstring",
		type = "resource",
		stackable = true,
		value = 500,
		rarity = "epic",
		description = "A bowstring pulsing with magical energy.",
	},

	-- === SHIELDS ===
	["Iron Shield"] = {
		id = "iron_shield",
		type = "armor",
		equipSlot = "Shield",
		defense = 10,
		combatReq = 15,
		stackable = false,
		value = 60,
		description = "A sturdy iron shield.",
	},
	["Gold Shield"] = {
		id = "gold_shield",
		type = "armor",
		equipSlot = "Shield",
		defense = 18,
		combatReq = 40,
		stackable = false,
		value = 250,
		description = "A gleaming gold shield.",
	},
	["Runite Shield"] = {
		id = "runite_shield",
		type = "armor",
		equipSlot = "Shield",
		defense = 30,
		combatReq = 70,
		stackable = false,
		value = 1500,
		description = "A nearly indestructible runite shield.",
	},
	["Dragon Shield"] = {
		id = "dragon_shield",
		type = "armor",
		equipSlot = "Shield",
		defense = 45,
		combatReq = 80,
		stackable = false,
		value = 7000,
		rarity = "legendary",
		description = "Forged from dragon scales.",
	},

	-- === MORE WEAPONS ===
	["Runite Sword"] = {
		id = "runite_sword",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 40,
		combatReq = 70,
		stackable = false,
		value = 2000,
		rarity = "epic",
		description = "A deadly runite blade.",
	},
	-- === PICKAXES ===
	["Bronze Pickaxe"] = {
		id = "bronze_pickaxe", type = "tool", equipSlot = "Tool", toolType = "pickaxe",
		levelReq = 1, skill = "Mining", gatherSpeed = 1.0, stackable = false, value = 10,
		description = "A basic bronze pickaxe.",
	},
	["Iron Pickaxe"] = {
		id = "iron_pickaxe", type = "tool", equipSlot = "Tool", toolType = "pickaxe",
		levelReq = 15, skill = "Mining", gatherSpeed = 0.8, stackable = false, value = 50,
		description = "A sturdy iron pickaxe.",
	},
	["Gold Pickaxe"] = {
		id = "gold_pickaxe", type = "tool", equipSlot = "Tool", toolType = "pickaxe",
		levelReq = 40, skill = "Mining", gatherSpeed = 0.6, stackable = false, value = 200,
		description = "A heavy gold pickaxe.",
	},
	["Runite Pickaxe"] = {
		id = "runite_pickaxe", type = "tool", equipSlot = "Tool", toolType = "pickaxe",
		levelReq = 70, skill = "Mining", gatherSpeed = 0.4, stackable = false, value = 1000,
		description = "The finest pickaxe money can buy.",
	},
	["Dragon Pickaxe"] = {
		id = "dragon_pickaxe", type = "tool", equipSlot = "Tool", toolType = "pickaxe",
		levelReq = 85, skill = "Mining", gatherSpeed = 0.3, stackable = false, value = 5000,
		rarity = "legendary", description = "Forged from dragonfire. Mines at incredible speed.",
	},

	-- === AXES (Woodcutting) ===
	["Bronze Axe"] = {
		id = "bronze_axe", type = "tool", equipSlot = "Tool", toolType = "axe",
		levelReq = 1, skill = "Woodcutting", gatherSpeed = 1.0, stackable = false, value = 10,
		description = "A basic bronze axe.",
	},
	["Iron Axe"] = {
		id = "iron_axe", type = "tool", equipSlot = "Tool", toolType = "axe",
		levelReq = 15, skill = "Woodcutting", gatherSpeed = 0.8, stackable = false, value = 50,
		description = "A sharp iron axe.",
	},
	["Gold Axe"] = {
		id = "gold_axe", type = "tool", equipSlot = "Tool", toolType = "axe",
		levelReq = 40, skill = "Woodcutting", gatherSpeed = 0.6, stackable = false, value = 200,
		description = "A gleaming gold axe.",
	},
	["Runite Axe"] = {
		id = "runite_axe", type = "tool", equipSlot = "Tool", toolType = "axe",
		levelReq = 70, skill = "Woodcutting", gatherSpeed = 0.4, stackable = false, value = 1000,
		description = "Cuts through anything.",
	},
	["Dragon Axe"] = {
		id = "dragon_axe", type = "tool", equipSlot = "Tool", toolType = "axe",
		levelReq = 85, skill = "Woodcutting", gatherSpeed = 0.3, stackable = false, value = 5000,
		rarity = "legendary", description = "The ultimate woodcutting tool.",
	},

	-- === FISHING RODS ===
	["Wooden Rod"] = {
		id = "wooden_rod", type = "tool", equipSlot = "Tool", toolType = "fishing_rod",
		levelReq = 1, skill = "Fishing", gatherSpeed = 1.0, stackable = false, value = 10,
		description = "A simple wooden fishing rod.",
	},
	["Iron Rod"] = {
		id = "iron_rod", type = "tool", equipSlot = "Tool", toolType = "fishing_rod",
		levelReq = 15, skill = "Fishing", gatherSpeed = 0.8, stackable = false, value = 50,
		description = "A rod with an iron reel.",
	},
	["Gold Rod"] = {
		id = "gold_rod", type = "tool", equipSlot = "Tool", toolType = "fishing_rod",
		levelReq = 40, skill = "Fishing", gatherSpeed = 0.6, stackable = false, value = 200,
		description = "A fine gold fishing rod.",
	},
	["Runite Rod"] = {
		id = "runite_rod", type = "tool", equipSlot = "Tool", toolType = "fishing_rod",
		levelReq = 70, skill = "Fishing", gatherSpeed = 0.4, stackable = false, value = 1000,
		description = "Fish practically leap onto this rod.",
	},
	["Dragon Rod"] = {
		id = "dragon_rod", type = "tool", equipSlot = "Tool", toolType = "fishing_rod",
		levelReq = 85, skill = "Fishing", gatherSpeed = 0.3, stackable = false, value = 5000,
		rarity = "legendary", description = "The fish don't stand a chance.",
	},

	-- === NEW BOSS DROP ITEMS ===
	-- King Rooster drops
	["Golden Feather"] = {
		id = "golden_feather",
		type = "material",
		rarity = "rare",
		stackable = true,
		value = 500,
		description = "A magnificent golden feather from the King Rooster.",
	},
	["King's Crest"] = {
		id = "kings_crest",
		type = "material",
		rarity = "uncommon",
		stackable = true,
		value = 750,
		description = "The royal crest of the chicken kingdom.",
	},

	-- Elder Treant drops
	["Heartwood"] = {
		id = "heartwood",
		type = "material",
		rarity = "rare",
		stackable = true,
		value = 1200,
		description = "The magical core wood of an ancient treant.",
	},
	["Ancient Bark"] = {
		id = "ancient_bark",
		type = "material",
		stackable = true,
		value = 200,
		description = "Bark from a millennia-old treant.",
	},
	["Elder Seed"] = {
		id = "elder_seed",
		type = "material",
		rarity = "epic",
		stackable = true,
		value = 3000,
		description = "A mystical seed that could grow into a great treant.",
	},

	-- Iron Golem drops
	["Golem Core"] = {
		id = "golem_core",
		type = "material",
		rarity = "epic",
		stackable = true,
		value = 5000,
		description = "The magical power source of an iron golem.",
	},
	["Golem Shield"] = {
		id = "golem_shield",
		type = "armor",
		equipSlot = "Shield",
		defBonus = 25,
		rarity = "rare",
		stackable = false,
		value = 2500,
		description = "A massive shield crafted from golem materials.",
	},

	-- Lake Serpent drops
	["Serpent Scale"] = {
		id = "serpent_scale",
		type = "material",
		rarity = "epic",
		stackable = true,
		value = 4000,
		description = "A shimmering scale from the legendary Lake Serpent.",
	},
	["Sea Fang"] = {
		id = "sea_fang",
		type = "weapon",
		damage = 35,
		rarity = "rare",
		stackable = false,
		value = 2000,
		description = "A sharp fang that can pierce through armor.",
	},
	["Serpent's Eye"] = {
		id = "serpents_eye",
		type = "material",
		rarity = "legendary",
		stackable = true,
		value = 10000,
		description = "The mystical eye of the Lake Serpent, pulsing with ancient magic.",
	},

	-- Corrupted Guardian drops
	["Guardian's Blessing"] = {
		id = "guardians_blessing",
		type = "material",
		rarity = "legendary",
		stackable = true,
		value = 15000,
		description = "A powerful blessing that purifies corruption and grants protection.",
	},
	["Corrupted Plate"] = {
		id = "corrupted_plate",
		type = "armor",
		equipSlot = "Body",
		defBonus = 40,
		rarity = "epic",
		stackable = false,
		value = 8000,
		description = "Heavy armor plate infused with dark magic.",
	},
	["Ancient Key"] = {
		id = "ancient_key",
		type = "material",
		rarity = "rare",
		stackable = true,
		value = 3000,
		description = "An ornate key that may unlock ancient mysteries.",
	},

	-- === CRIMSON WARLORD DROPS (Mid-Tier Boss) ===

	["Warlord's Greatsword"] = {
		id = "warlords_greatsword",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 55,
		weaponType = "sword",
		levelReq = 50,
		rarity = "epic",
		stackable = false,
		value = 12000,
		description = "A massive crimson-edged greatsword. The Warlord's signature weapon — its blade still burns with fury.",
	},
	["Crimson Platebody"] = {
		id = "crimson_platebody",
		type = "armor",
		equipSlot = "Body",
		defBonus = 35,
		levelReq = 50,
		rarity = "epic",
		stackable = false,
		value = 10000,
		description = "Blood-red armor forged in battle. Offers excellent protection with a menacing presence.",
	},
	["Crimson Platelegs"] = {
		id = "crimson_platelegs",
		type = "armor",
		equipSlot = "Legs",
		defBonus = 28,
		levelReq = 50,
		rarity = "epic",
		stackable = false,
		value = 8000,
		description = "Heavy crimson leg armor. The Warlord's greaves, still warm to the touch.",
	},
	["Warlord's Helm"] = {
		id = "warlords_helm",
		type = "armor",
		equipSlot = "Head",
		defBonus = 22,
		levelReq = 50,
		rarity = "epic",
		stackable = false,
		value = 9000,
		description = "A horned helm of dark iron, crowned with a burning ruby. Intimidation incarnate.",
	},
	["Crimson Cape"] = {
		id = "crimson_cape",
		type = "armor",
		equipSlot = "Cape",
		defBonus = 12,
		levelReq = 50,
		rarity = "legendary",
		stackable = false,
		value = 20000,
		description = "The Warlord's battle cape — torn, bloodstained, legendary. The rarest drop in the safe zone.",
	},
	["Warlord's Shield"] = {
		id = "warlords_shield",
		type = "armor",
		equipSlot = "Shield",
		defBonus = 30,
		levelReq = 50,
		rarity = "epic",
		stackable = false,
		value = 11000,
		description = "A heavy crimson shield bearing the Warlord's crest. Absorbs punishment like nothing else.",
	},
	["Blood Rune"] = {
		id = "blood_rune",
		type = "material",
		rarity = "rare",
		stackable = true,
		value = 500,
		description = "A rune infused with blood magic. Used in high-level crafting.",
	},

	-- === NEW AREA MONSTER DROPS (MapSetup5) ===
	
	-- Pirate Ghost drops
	["Ghost Doubloon"] = {
		id = "ghost_doubloon",
		type = "currency",
		rarity = "uncommon",
		stackable = true,
		value = 25,
		description = "A spectral coin from the world beyond.",
	},
	["Pirate Cutlass"] = {
		id = "pirate_cutlass",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 22,
		combatReq = 25,
		rarity = "uncommon",
		stackable = false,
		value = 150,
		description = "A curved blade favored by ghostly pirates.",
	},
	["Spectral Cloth"] = {
		id = "spectral_cloth",
		type = "material",
		rarity = "uncommon",
		stackable = true,
		value = 40,
		description = "Ethereal fabric that phases between worlds.",
	},
	
	-- Ice Elemental drops
	["Frozen Shard"] = {
		id = "frozen_shard",
		type = "material",
		rarity = "uncommon",
		stackable = true,
		value = 30,
		description = "A shard of pure ice that never melts.",
	},
	["Ice Crystal"] = {
		id = "ice_crystal",
		type = "material",
		rarity = "rare",
		stackable = true,
		value = 120,
		description = "A perfect crystal formed in the heart of winter.",
	},
	["Frost Essence"] = {
		id = "frost_essence",
		type = "material",
		rarity = "epic",
		stackable = true,
		value = 300,
		description = "The very essence of eternal winter.",
	},
	["Permafrost Ore"] = {
		id = "permafrost_ore",
		type = "resource",
		rarity = "uncommon",
		skill = "Mining",
		levelReq = 30,
		xp = 50,
		stackable = true,
		value = 45,
		description = "Ore that remains frozen even in fire.",
	},
	
	-- Lava Golem drops
	["Magma Core"] = {
		id = "magma_core",
		type = "material",
		rarity = "epic",
		stackable = true,
		value = 400,
		description = "The molten heart of a lava golem.",
	},
	["Obsidian Shard"] = {
		id = "obsidian_shard",
		type = "material",
		rarity = "uncommon",
		stackable = true,
		value = 35,
		description = "Sharp volcanic glass formed in extreme heat.",
	},
	["Volcanic Ash"] = {
		id = "volcanic_ash",
		type = "material",
		rarity = "common",
		stackable = true,
		value = 8,
		description = "Fine ash from volcanic eruptions.",
	},
	["Lava Blade"] = {
		id = "lava_blade",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 45,
		combatReq = 55,
		rarity = "epic",
		stackable = false,
		value = 800,
		description = "A blade forged in the heart of a volcano, glowing with internal fire.",
	},
	
	-- Fairy Dragon drops
	["Fairy Dust"] = {
		id = "fairy_dust",
		type = "material",
		rarity = "uncommon",
		stackable = true,
		value = 20,
		description = "Magical dust that sparkles with rainbow colors.",
	},
	["Dragon Scale"] = {
		id = "dragon_scale",
		type = "material",
		rarity = "rare",
		stackable = true,
		value = 150,
		description = "A scale from a mighty dragon, shimmering with magic.",
	},
	["Enchanted Petal"] = {
		id = "enchanted_petal",
		type = "material",
		rarity = "uncommon",
		stackable = true,
		value = 25,
		description = "A flower petal infused with fairy magic.",
	},
	["Rainbow Gem"] = {
		id = "rainbow_gem",
		type = "material",
		rarity = "epic",
		stackable = true,
		value = 500,
		description = "A rare gem that refracts light into beautiful rainbows.",
	},
	
	-- Ancient Guardian drops
	["Ancient Relic"] = {
		id = "ancient_relic",
		type = "material",
		rarity = "epic",
		stackable = true,
		value = 600,
		description = "A mysterious artifact from a lost civilization.",
	},
	["Guardian Essence"] = {
		id = "guardian_essence",
		type = "material",
		rarity = "rare",
		stackable = true,
		value = 250,
		description = "The protective spirit of an ancient guardian.",
	},
	["Rune of Power"] = {
		id = "rune_of_power",
		type = "material",
		rarity = "legendary",
		stackable = true,
		value = 1500,
		description = "A mystical rune that pulses with ancient power.",
	},
	["Ancient Armor"] = {
		id = "ancient_armor",
		type = "armor",
		equipSlot = "Body",
		combatReq = 70,
		rarity = "legendary",
		stackable = false,
		value = 2000,
		defense = 35,
		description = "Armor forged by masters of a forgotten age.",
	},
	
	-- Frost Wyrm drops
	["Wyrm Scale"] = {
		id = "wyrm_scale",
		type = "material",
		rarity = "rare",
		stackable = true,
		value = 180,
		description = "A crystalline scale from a frost wyrm.",
	},
	["Frozen Heart"] = {
		id = "frozen_heart",
		type = "material",
		rarity = "legendary",
		stackable = true,
		value = 1200,
		description = "The still-beating heart of a frost wyrm, forever frozen.",
	},
	["Ice Fang"] = {
		id = "ice_fang",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 38,
		combatReq = 60,
		rarity = "rare",
		stackable = false,
		value = 600,
		description = "A fang weapon that chills enemies to the bone.",
	},
	["Frost Armor"] = {
		id = "frost_armor",
		type = "armor",
		equipSlot = "Body",
		combatReq = 60,
		rarity = "rare",
		stackable = false,
		value = 800,
		defense = 28,
		description = "Armor that emanates a perpetual chill.",
	},

	-- === LICH KING MALACHAR DROPS ===
	["Lich Crown"] = {
		id = "lich_crown",
		type = "armor",
		equipSlot = "Head",
		combatReq = 85,
		rarity = "legendary",
		stackable = false,
		value = 12000,
		defense = 40,
		description = "A crown of bone and shadow, pulsing with necrotic power.",
	},
	["Soul Staff"] = {
		id = "soul_staff",
		type = "weapon",
		equipSlot = "Weapon",
		combatReq = 85,
		rarity = "legendary",
		stackable = false,
		value = 15000,
		damage = 55,
		attackSpeed = 1.0,
		description = "A staff that drains the very essence of life from its victims.",
	},
	["Dark Essence"] = {
		id = "dark_essence",
		type = "material",
		rarity = "epic",
		stackable = true,
		value = 2000,
		description = "Pure concentrated darkness, harvested from the Lich King's domain.",
	},
	["Necrotic Robe"] = {
		id = "necrotic_robe",
		type = "armor",
		equipSlot = "Body",
		combatReq = 80,
		rarity = "epic",
		stackable = false,
		value = 6000,
		defense = 32,
		description = "Robes woven from the fabric between life and death.",
	},
	["Bone Dust"] = {
		id = "bone_dust",
		type = "material",
		rarity = "uncommon",
		stackable = true,
		value = 15,
		description = "Fine powder ground from ancient bones. Used in dark rituals.",
	},

	-- === PRESTIGE CAPES ===
	["Prestige Cape I"] = {
		id = "prestige_cape_1",
		type = "armor",
		equipSlot = "Cape",
		defense = 5,
		rarity = "rare",
		value = 0,
		premium = false,
		tradeable = false,
		droppable = false,
		stackable = false,
		prestige = 1,
		description = "First prestige. The journey begins anew.",
	},
	["Prestige Cape II"] = {
		id = "prestige_cape_2",
		type = "armor",
		equipSlot = "Cape",
		defense = 10,
		rarity = "rare",
		value = 0,
		tradeable = false,
		droppable = false,
		stackable = false,
		prestige = 2,
		description = "Second prestige. Wisdom through repetition.",
	},
	["Prestige Cape III"] = {
		id = "prestige_cape_3",
		type = "armor",
		equipSlot = "Cape",
		defense = 15,
		rarity = "epic",
		value = 0,
		tradeable = false,
		droppable = false,
		stackable = false,
		prestige = 3,
		description = "Third prestige. Mastery takes shape.",
	},
	["Prestige Cape IV"] = {
		id = "prestige_cape_4",
		type = "armor",
		equipSlot = "Cape",
		defense = 20,
		rarity = "epic",
		value = 0,
		tradeable = false,
		droppable = false,
		stackable = false,
		prestige = 4,
		description = "Fourth prestige. Few reach this height.",
	},
	["Prestige Cape V"] = {
		id = "prestige_cape_5",
		type = "armor",
		equipSlot = "Cape",
		defense = 25,
		rarity = "epic",
		value = 0,
		tradeable = false,
		droppable = false,
		stackable = false,
		prestige = 5,
		description = "Fifth prestige. Halfway to legend.",
	},
	["Prestige Cape VI"] = {
		id = "prestige_cape_6",
		type = "armor",
		equipSlot = "Cape",
		defense = 30,
		rarity = "legendary",
		value = 0,
		tradeable = false,
		droppable = false,
		stackable = false,
		prestige = 6,
		description = "Sixth prestige. The grind is real.",
	},
	["Prestige Cape VII"] = {
		id = "prestige_cape_7",
		type = "armor",
		equipSlot = "Cape",
		defense = 35,
		rarity = "legendary",
		value = 0,
		tradeable = false,
		droppable = false,
		stackable = false,
		prestige = 7,
		description = "Seventh prestige. Feared and respected.",
	},
	["Prestige Cape VIII"] = {
		id = "prestige_cape_8",
		type = "armor",
		equipSlot = "Cape",
		defense = 40,
		rarity = "legendary",
		value = 0,
		tradeable = false,
		droppable = false,
		stackable = false,
		prestige = 8,
		description = "Eighth prestige. Ascension approaches.",
	},
	["Prestige Cape IX"] = {
		id = "prestige_cape_9",
		type = "armor",
		equipSlot = "Cape",
		defense = 45,
		rarity = "legendary",
		value = 0,
		tradeable = false,
		droppable = false,
		stackable = false,
		prestige = 9,
		description = "Ninth prestige. One step from godhood.",
	},
	["Prestige Cape X"] = {
		id = "prestige_cape_10",
		type = "armor",
		equipSlot = "Cape",
		defense = 50,
		rarity = "legendary",
		value = 0,
		tradeable = false,
		droppable = false,
		stackable = false,
		prestige = 10,
		description = "Tenth prestige. A living legend. The universe bows.",
	},

	-- === PREMIUM GEAR - TIER 30 "STARWEAVE" SET ===
	["Starweave Sword"] = {
		id = "starweave_sword",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 22,
		rarity = "rare",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 50,
		description = "Forged from fallen starlight. Cuts through darkness.",
	},
	["Starweave Helm"] = {
		id = "starweave_helm",
		type = "armor",
		equipSlot = "Head",
		defense = 12,
		rarity = "rare",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 50,
		description = "A celestial helmet forged from starweave metal, shimmering with silver and blue light.",
	},
	["Starweave Platebody"] = {
		id = "starweave_platebody",
		type = "armor",
		equipSlot = "Body",
		defense = 18,
		rarity = "rare",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 50,
		description = "An elegant chestplate woven from stardust and moonbeams, providing divine protection.",
	},
	["Starweave Platelegs"] = {
		id = "starweave_platelegs",
		type = "armor",
		equipSlot = "Legs",
		defense = 15,
		rarity = "rare",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 50,
		description = "Leg armor that gleams with celestial energy, lighter than silk yet stronger than steel.",
	},
	["Starweave Shield"] = {
		id = "starweave_shield",
		type = "armor",
		equipSlot = "Shield",
		defense = 14,
		rarity = "rare",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 50,
		description = "A shield crafted from cosmic energies, capable of deflecting even the darkest magic.",
	},

	-- === PREMIUM GEAR - TIER 50 "EMBERFROST" SET ===
	["Emberfrost Blade"] = {
		id = "emberfrost_blade",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 35,
		rarity = "epic",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 100,
		description = "A sword that burns with eternal flame yet remains cold to the touch. Fire and ice in perfect balance.",
	},
	["Emberfrost Crown"] = {
		id = "emberfrost_crown",
		type = "armor",
		equipSlot = "Head",
		defense = 20,
		rarity = "epic",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 100,
		description = "A crown that channels the opposing forces of fire and frost, granting wisdom through duality.",
	},
	["Emberfrost Platebody"] = {
		id = "emberfrost_platebody",
		type = "armor",
		equipSlot = "Body",
		defense = 28,
		rarity = "epic",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 100,
		description = "Armor that pulses with orange flames on one side and cyan frost on the other, creating perfect equilibrium.",
	},
	["Emberfrost Platelegs"] = {
		id = "emberfrost_platelegs",
		type = "armor",
		equipSlot = "Legs",
		defense = 24,
		rarity = "epic",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 100,
		description = "Leg guards that embody the eternal struggle between heat and cold, forged in the heart of a frozen volcano.",
	},
	["Emberfrost Bulwark"] = {
		id = "emberfrost_bulwark",
		type = "armor",
		equipSlot = "Shield",
		defense = 22,
		rarity = "epic",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 100,
		description = "A shield that can withstand any temperature, from the deepest freeze to the hottest inferno.",
	},

	-- === PREMIUM GEAR - TIER 65 "VOIDBORN" SET ===
	["Voidborn Greatsword"] = {
		id = "voidborn_greatsword",
		type = "weapon",
		equipSlot = "Weapon",
		damage = 48,
		rarity = "legendary",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 500,
		description = "Forged in the space between worlds, this blade cuts through reality itself. Gold veins pulse with otherworldly power.",
	},
	["Voidborn Visage"] = {
		id = "voidborn_visage",
		type = "armor",
		equipSlot = "Head",
		defense = 28,
		rarity = "legendary",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 500,
		description = "A helm that peers into the void itself. Those who wear it can see truths that others cannot.",
	},
	["Voidborn Platebody"] = {
		id = "voidborn_platebody",
		type = "armor",
		equipSlot = "Body",
		defense = 38,
		rarity = "legendary",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 500,
		description = "Armor woven from the fabric of the void, adorned with golden accents that bind the darkness within.",
	},
	["Voidborn Platelegs"] = {
		id = "voidborn_platelegs",
		type = "armor",
		equipSlot = "Legs",
		defense = 33,
		rarity = "legendary",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 500,
		description = "Leg armor that draws power from the endless void, strengthened by threads of pure gold.",
	},
	["Voidborn Aegis"] = {
		id = "voidborn_aegis",
		type = "armor",
		equipSlot = "Shield",
		defense = 30,
		rarity = "legendary",
		stackable = false,
		tradeable = false,
		droppable = false,
		value = 0,
		premium = true,
		robuxPrice = 500,
		description = "A shield that exists partially in the void, making it nearly impossible to damage or destroy.",
	},
}

-- Auto-assign rarity based on value if not set
for name, item in pairs(ItemDatabase.Items) do
	if not item.rarity then
		local v = item.value or 0
		if v >= 1000 then
			item.rarity = "legendary"
		elseif v >= 200 then
			item.rarity = "epic"
		elseif v >= 50 then
			item.rarity = "rare"
		elseif v >= 10 then
			item.rarity = "uncommon"
		else
			item.rarity = "common"
		end
	end
end

-- Helper: get item by name
function ItemDatabase.GetItem(name)
	return ItemDatabase.Items[name]
end

-- Helper: get all items for a skill
function ItemDatabase.GetItemsBySkill(skill)
	local results = {}
	for name, item in pairs(ItemDatabase.Items) do
		if item.skill == skill then
			results[name] = item
		end
	end
	return results
end

-- Helper: get wilderness-only items
function ItemDatabase.GetWildernessItems()
	local results = {}
	for name, item in pairs(ItemDatabase.Items) do
		if item.wildernessOnly then
			results[name] = item
		end
	end
	return results
end

-- Helper: get all items matching a type (food, weapon, armor, resource, currency, crafted, etc.)
function ItemDatabase.GetItemsByType(itemType)
	local results = {}
	for name, item in pairs(ItemDatabase.Items) do
		if item.type == itemType then
			results[name] = item
		end
	end
	return results
end

return ItemDatabase
